//Question first
//let gmaths=Number(prompt("enter marks:"));
//let gscience=Number(prompt("enter marks:"));
//if(gmaths>=90 && gscience>=90){
//    "the student is eligible for full scholarship"
//}
//else if(gmaths>=90 && gscience>=80){
 //   "the student is eligible for partial scholarship"
//}
//else if(gmaths>=80 && gscience>=90){
 //   "the student is eligible for partial scholarship"
//}
//else {
  //  " the student is not eligible for scholarship "
//}
// second question
//let a=Number(prompt("enter first side of triangle:"));
//let b=Number(prompt("enter second side of triangle:"));
//let c=Number(prompt("enter third side of triangle:"));
//if (a==b==c){
 //   "Triangle is an equilateral triangle"
//}
//else if(a==b!=c && b==c!=a && a==c!=b){
 //   "triangle is an isoceles triangle"
//}
//else if(a!=b!=c){
 //   "triangle is scalene"
//}
//else{
 //   "invalid"
//}
// third question
//let age=prompt("enter age of a person:");
//let fare=age<3?" ticket is free":age>=3 && age<=12?"ticket is $10":age>12?"ticket is $15":"invalid age";
//console.log(fare);
// 4 question
//let weight=prompt("enter weight in pounds:");
//let cost=weight<=2?" cost is $5":weight>=3 && weight<=5?"cost is $10":weight>5?"cost is $15":"invalid ";
//console.log(cost);
//question 5
//let w=prompt("enter weight in kilograms:")
//let h=prompt("enter height of person in metres:")
//BMI=w/h**2
//if(BMI<18.5){
 //   "UNDERWEIGHT"
//}
//else if(BMI>=18.5 && BMI<=24.9){
  //  "NORMAL"
//}
//else if(BMI<=25 && BMI<=29.9){
  //  "OVERWEIGHT"
//}
//else if(BMI>=30){
 //   "OBESE"
//}
//else{
  //  "invalid"
//}
// question 6
s